version: '3.8'
services:
  webapp:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - prometheus
  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - '9100:9100'
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - '9090:9090'
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_PROVISIONING_DASHBOARDS_ENABLED=true
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - '3000:3000'