global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:5000']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
