global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'render-app'
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['devops-final-project-fbg8.onrender.com']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
