global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'webapp'
    static_configs:
      - targets: ['webapp:5000']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']