{
 "title": "App & Local Machine Overview final dash",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Services",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "service_tracker_total_services" }
   ]
  },
  {
   "title": "Active Services",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_tracker_active_services"
    }
   ]
  },
  {
   "title": "Inactive Services",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_tracker_inactive_services"
    }
   ]
  },
  {
   "title": "Disk Usage (Root)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{device=\"/dev/sdg\",device_error=\"\",fstype=\"ext4\",mountpoint=\"/etc/hostname\"} - node_filesystem_free_bytes{device=\"/dev/sdg\",device_error=\"\",fstype=\"ext4\",mountpoint=\"/etc/hostname\"}) / node_filesystem_size_bytes{device=\"/dev/sdg\",device_error=\"\",fstype=\"ext4\",mountpoint=\"/etc/hostname\"} * 100"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1-(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100"
    }
   ]
  },
  {
   "title": "Total Requests (my-service)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "service_tracker_total_requests" }
   ]
  },
  {
   "title": "Disk Total / Free",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/sdg\",device_error=\"\",fstype=\"ext4\",mountpoint=\"/etc/hostname\"}/1000",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "node_filesystem_free_bytes{device=\"/dev/sdg\",device_error=\"\",fstype=\"ext4\",mountpoint=\"/etc/hostname\"}/1000",
     "legendFormat": "FREE"
    }
   ]
  },
  {
   "title": "RAM Total / Free",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "TOTAL" },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "FREE" }
   ]
  },
  {
   "title": "Uptime ratio per Service",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "service_tracker_uptime_ratio*100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100"
    }
   ]
  }
 ]
}