name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-python-3-10:
    name: Lint Python
    uses: ./.github/workflows/reusable-quality.yml
    with:
      python-version: '3.10'
      action: 'lint'

  test-python-3-9:
    name: Test Python
    uses: ./.github/workflows/reusable-quality.yml
    with:
      python-version: '3.9'
      action: 'test'

  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [lint-python-3-10, test-python-3-9]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t alexnouriev/devops-final-project:${{ github.sha }} .

