name: CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        run: |
          docker build . \
            -t ${{ secrets.DOCKERHUB_USER }}/student-grades:latest
          docker push ${{ secrets.DOCKERHUB_USER }}/student-grades:latest

      - name: Trigger Render Deploy Hook
        # ודא שהגדרת את ה‑RENDER_DEPLOY_HOOK_URL ב‑GitHub Secrets
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
